//1 GLOBAL PHASE --> THIS 

//MEMORY PHASE --> VAL1=UNDEFINED 

//EXECUTION PHASE-> VAL1=20

//WHEN A METHOD COMES IT WILL AGAIN FOLLOW THE SAME MEMORY PHASE AND THEN EXECUTION PHASE

// IF THREE METHODS CALL EACH OTHER IN ONE ANOTHER THEN THE  IT WILL FOLLOW LIFO 